src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 * @Vich\Uploadable
 * @ORM\HasLifecycleCallbacks()
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank
     * @Assert\Length(
     *      max = 255,
     *      allowEmptyString = false
     * )
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $short_description;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $long_description;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     * @Assert\NotBlank
     * @Assert\PositiveOrZero
     */
    private $price_euro;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     * @Assert\Range(
     *      max = 99,
     * )
     * @Assert\PositiveOrZero
     */
    private $price_centime;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(
     *      max = 255,
     *      allowEmptyString = false
     * )
     */
    private $img_alt;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $enabled;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="products")
     */
    private $tags;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Picture", mappedBy="product")
     */
    private $pictures;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string
     */
    private $icon;

    /**
     * @Vich\UploadableField(mapping="product_icons", fileNameProperty="icon")
     * @var File
     */
    private $iconFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="product_images", fileNameProperty="image")
     * @var File
     */
    private $imageFile;


    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Ingredient", inversedBy="products")
     */
    private $ingredients;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Unit")
     */
    private $unit;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Allergen", inversedBy="products")
     */
    private $allergens;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->pictures = new ArrayCollection();
        $this->ingredients = new ArrayCollection();
        $this->allergens = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(?string $short_description): self
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function getLongDescription(): ?string
    {
        return $this->long_description;
    }

    public function setLongDescription(?string $long_description): self
    {
        $this->long_description = $long_description;

        return $this;
    }

    public function getEnabled(): ?bool
    {
        return $this->enabled;
    }

    public function setEnabled(?bool $enabled): self
    {
        $this->enabled = $enabled;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    /**
     * @return Collection|picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setProduct($this);
        }

        return $this;
    }

    public function removePicture(picture $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getProduct() === $this) {
                $picture->setProduct(null);
            }
        }

        return $this;
    }

    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updated_at = new \DateTime();
        }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function setImage($image)
    {
        $this->image = $image;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setIconFile(File $icon = null)
    {
        $this->iconFile = $icon;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($icon) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updated_at = new \DateTime();
        }
    }

    public function getIconFile()
    {
        return $this->iconFile;
    }

    public function setIcon($icon)
    {
        $this->icon = $icon;
    }

    public function getIcon()
    {
        return $this->icon;
    }

    /**
     * @return Collection|ingredient[]
     */
    public function getIngredients(): Collection
    {
        return $this->ingredients;
    }

    public function addIngredient(ingredient $ingredient): self
    {
        if (!$this->ingredients->contains($ingredient)) {
            $this->ingredients[] = $ingredient;
        }

        return $this;
    }

    public function removeIngredient(ingredient $ingredient): self
    {
        if ($this->ingredients->contains($ingredient)) {
            $this->ingredients->removeElement($ingredient);
        }

        return $this;
    }

    public function getUnit(): ?unit
    {
        return $this->unit;
    }

    public function setUnit(?unit $unit): self
    {
        $this->unit = $unit;

        return $this;
    }

    /**
     * @return Collection|allergen[]
     */
    public function getAllergens(): Collection
    {
        return $this->allergens;
    }

    public function addAllergen(allergen $allergen): self
    {
        if (!$this->allergens->contains($allergen)) {
            $this->allergens[] = $allergen;
        }

        return $this;
    }

    public function removeAllergen(allergen $allergen): self
    {
        if ($this->allergens->contains($allergen)) {
            $this->allergens->removeElement($allergen);
        }

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function __toString()
    {
        return $this->title;
    }

    /** 
     * @ORM\PrePersist
     */
    public function generateCreatedAt()
    {
        $this->created_at = new \DateTime();
        if(empty($this->img_alt)){
            $this->img_alt = $this->title . " image";
        }
    }

    /** 
     * @ORM\PreUpdate
     */
    public function generateUpdatedAt()
    {
        $this->updated_at = new \DateTime();
        if(empty($this->img_alt)){
            $this->img_alt = $this->title . " image";
        }
    }

    public function getPriceEuro(): ?int
    {
        return $this->price_euro;
    }

    public function setPriceEuro(?int $price_euro): self
    {
        $this->price_euro = $price_euro;

        return $this;
    }

    public function getPriceCentime(): ?int
    {
        return $this->price_centime;
    }

    public function setPriceCentime(?int $price_centime): self
    {
        $this->price_centime = $price_centime;

        return $this;
    }

    public function getImgAlt(): ?string
    {
        return $this->img_alt;
    }

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Repository\ProductRepository;
use App\Repository\TagRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function home(ProductRepository $productRepository)
    {
        return $this->render('main\home.html.twig', [
            'products' => $productRepository->findBy(
                ['enabled' => 'true'],
                ['updated_at' => 'DESC']
            ),
        ]);
    }

    /**
     * @Route("/about-us", name="about_us")
     */
    public function about_us()
    {
        return $this->render('main\about-us.html.twig', [
        ]);
    }

    /**
     * @Route("/faq", name="faq")
     */
    public function faq()
    {
        return $this->render('main\faq.html.twig', [
        ]);
    }

    /**
     * @Route("/delivery", name="delivery")
     */
    public function delivery()
    {
        return $this->render('main\delivery.html.twig', [
        ]);
    }

    /**
     * @Route("/legal", name="legal")
     */
    public function legal()
    {
        return $this->render('main\legal.html.twig', [
        ]);
    }

    /**
     * @Route("/payment", name="payment")
     */
    public function payment()
    {
        return $this->render('main\payment.html.twig', [
        ]);
    }

    /**
     * @Route("/cakes", name="cakes")
     */
    public function cakes(ProductRepository $productRepository)
    {
        return $this->render('main\cakes.html.twig', [
            'products' => $productRepository->findByProductType('cake'),
        ]);
    }

    /**
     * @Route("/chocolates", name="chocolates")
     */
    public function chocolates(ProductRepository $productRepository)
    {
        return $this->render('main\chocolates.html.twig', [
            'products' => $productRepository->findByProductType('chocolate'),
        ]);
    }

    /**
     * @Route("/product/{id<\d+>}", name="product")
     */
    public function product(Product $product)
    {
        return $this->render('main\product.html.twig', [
            'product' => $product,
        ]);
    }

    /**
     * @Route("/product/tag/{id<\d+>}", name="products_by_tag")
     */
    public function productsByTag($id, TagRepository $tagRepository)
    {
        return $this->render('main\products_by_tag.html.twig', [
            'tag' => $tagRepository->find($id),
        ]);
    }
}

templates/main/about-us.html.twig
{% extends 'base.html.twig' %}

{% block title %}Au'raw - About us{% endblock %}

{% block body %}

<div class="form__picture">
    <img src="{{ asset('static_pics/2d69eb8fb3f9b70d4ea546c57402a499.jpg') }}" alt="beatuiful picture">
    <div class="form__container">
        <h1>Who Are We?</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus nostrum tenetur pariatur hic consequuntur. Placeat sint fuga veritatis consequatur. Odio numquam aspernatur impedit dolor ratione officiis iure totam adipisci reprehenderit.</p>
        <br>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Inventore voluptate non esse minima at placeat deleniti dolorum recusandae blanditiis repellat praesentium distinctio quos sit magnam, soluta fuga? Harum odit tenetur dolorem, soluta optio excepturi incidunt praesentium ipsam maiores non odio quisquam atque repudiandae? Culpa optio ratione id, necessitatibus aut saepe!</p>
        <br>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolore, eos?</p>
        <br>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus nostrum tenetur pariatur hic consequuntur. Placeat sint fuga veritatis consequatur. Odio numquam aspernatur impedit dolor ratione officiis iure totam adipisci reprehenderit.</p>
    </div>
</div>

{% endblock %}

templates/main/cakes.html.twig
{% extends 'base.html.twig' %}

{% block title %}Au'raw - Cakes{% endblock %}

{% block body %}

        <div class="top-part__container">
            {% if products|length > 3 %}
             <div id="promo-cakes">
               <!-- Slideshow container -->
                <div class="slideshow-container">
                    {% for i in 0..3 %}
                    <!-- Full-width images with number and caption text -->
                
                    <div class="mySlides fade">
                        <div class="numbertext">{{ i + 1 }} / 4</div>
                            <a href="{{ path('product', {'id': products[i].id}) }}">
                                <img src="{{ asset('uploads/images/products/'~ products[i].icon) }}" atl="{{ products[i].imgAlt }}">
                            </a>
                        <div class="text">{{products[i].title}}</div>
                    </div>
                    {% endfor %}
                    <!-- Next and previous buttons -->
                    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                    <a class="next" onclick="plusSlides(1)">&#10095;</a>
                </div>
                
                <!-- The dots/circles -->
                <div style="text-align:center">
                    <span class="dot" onclick="currentSlide(1)"></span>
                    <span class="dot" onclick="currentSlide(2)"></span>
                    <span class="dot" onclick="currentSlide(3)"></span>
                    <span class="dot" onclick="currentSlide(4)"></span>
                </div>
            </div>
            {% endif %}
        </div>
       
<div class="bottom-part__container">

    {% for product in products %}
        <a href="{{ path('product', {'id': product.id}) }}" class="product">
            <div class="product-item">
                <img src="{{ asset('uploads/images/products/'~ product.icon) }}" atl="{{ product.imgAlt }}">
                <div class="name">
                    <h1>{{ product.title }}</h1>
                </div>
                <div class="description">
                    <p class="product-description">{{ product.shortDescription }}</p>
                </div>
                    <p class="product-price--list">{{ product.priceEuro }}<sup>{{ "%02d"|format(product.priceCentime) }}</sup> &euro; <em>/ {{ product.unit.title }}</em></p>
            </div>
        </a>
    {% endfor %}
</div>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="{{ asset('js/carousel.js') }}"></script>
{% endblock %}

templates/main/chocolates.html.twig
{% extends 'base.html.twig' %}

{% block title %}Au'raw - Chocolates{% endblock %}

{% block body %}

        <div class="top-part__container">
            {% if products|length > 3 %}
             <div id="promo-chocolates">
               <!-- Slideshow container -->
                <div class="slideshow-container">
                    {% for i in 0..3 %}
                    <!-- Full-width images with number and caption text -->
                
                    <div class="mySlides fade">
                        <div class="numbertext">{{ i + 1 }} / 4</div>
                            <a href="{{ path('product', {'id': products[i].id}) }}">
                                <img src="{{ asset('uploads/images/products/'~ products[i].icon) }}" atl="{{ products[i].imgAlt }}">
                            </a>
                        <div class="text">{{products[i].title}}</div>
                    </div>
                    {% endfor %}
                    <!-- Next and previous buttons -->
                    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                    <a class="next" onclick="plusSlides(1)">&#10095;</a>
                </div>
                
                <!-- The dots/circles -->
                <div style="text-align:center">
                    <span class="dot" onclick="currentSlide(1)"></span>
                    <span class="dot" onclick="currentSlide(2)"></span>
                    <span class="dot" onclick="currentSlide(3)"></span>
                    <span class="dot" onclick="currentSlide(4)"></span>
                </div>
            </div>
            {% endif %}
        </div>
       
<div class="bottom-part__container">

    {% for product in products %}
        <a href="{{ path('product', {'id': product.id}) }}" class="product">
            <div class="product-item">
                <img src="{{ asset('uploads/images/products/'~ product.icon) }}" atl="{{ product.imgAlt }}">
                <div class="name">
                    <h1>{{ product.title }}</h1>
                </div>
                <div class="description">
                    <p class="product-description">{{ product.shortDescription }}</p>
                </div>
                    <p class="product-price--list">{{ product.priceEuro }}<sup>{{ "%02d"|format(product.priceCentime) }}</sup> &euro; <em>/ {{ product.unit.title }}</em></p>
            </div>
        </a>
    {% endfor %}
</div>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="{{ asset('js/carousel.js') }}"></script>
{% endblock %}

templates/main/contact-us.html.twig
{% extends 'base.html.twig' %}

{% block title %}Au'raw - Contact us{% endblock %}

{% block body %}

<div class="form__picture">
    <img src="{{ asset('static_pics/low-cal.jpg') }}" alt="beatuiful picture">

    <div class="form__container">
        {{ form_start(form) }}
            <p>
            {{ form_label(form.name, 'Your Name') }}
            {{ form_widget(form.name, {
                        'attr': {
                        'placeholder': 'How do we address you?',
                        }
                    })
                    }}
            {{ form_errors(form.name) }}
            </p>
            <br>
            <p>
            {{ form_label(form.email, 'Your Email') }}
            <section id="asterisk">Please, provide at least your emailn so we can get back to you!</label></section>
            {{ form_widget(form.email, {
                        'attr': {
                        'placeholder': 'e.g. sarah@gmail.com',
                        }
                    })
                    }}
            {{ form_errors(form.email) }}
            </p>

            <p>
            {{ form_label(form.phone_number, 'Your Phone Number') }}
            <section id="asterisk">If you prefer us to call you, make sure to provide your phone number too!</label></section>
            {{ form_widget(form.phone_number, {
                        'attr': {
                        'placeholder': '06 01 00 00 00',
                        }
                    }) }}
            {{ form_errors(form.phone_number) }}
            </p>
            <br>
            <p>
            {{ form_label(form.text, 'Your Message') }}
            {{ form_widget(form.text, {
                        'attr': {
                        'placeholder': 'Would you like to order something? Do you need our advice?',
                        }
                    })
                    }}
            {{ form_errors(form.text) }}
            </p>
            <button class="btn">{{ button_label|default('Send us a message!') }}</button>
        {{ form_end(form) }}

    </div>
</div>

{% endblock %}

templates/main/delivery.html.twig
{% extends 'base.html.twig' %}

{% block title %}Au-raw - Delivery{% endblock %}

{% block body %}

<div class="form__picture">
            <img src="{{ asset('static_pics/mango-turmeric-raw-cupcakes-4.jpg') }}" alt="beatuiful picture">

            <div class="form__container">
                <h1>Delivery Information</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis cumque, porro, tenetur voluptatibus neque dolores quasi, ex adipisci labore quisquam laboriosam. Maxime voluptatibus officia numquam ea iste! Exercitationem, aperiam possimus?</p>
                <br>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Inventore voluptate non esse minima at placeat deleniti dolorum recusandae blanditiis repellat praesentium distinctio quos sit magnam, soluta fuga? Harum odit tenetur dolorem, soluta optio excepturi incidunt praesentium ipsam maiores non odio quisquam atque repudiandae?</p>
                <br>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolore, eos?</p>
                <br>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus nostrum tenetur pariatur hic consequuntur. Placeat sint fuga veritatis consequatur. Odio numquam aspernatur impedit dolor ratione officiis iure totam adipisci reprehenderit.</p>
            </div>
        </div>

{% endblock %}

templates/main/faq.html.twig
{% extends 'base.html.twig' %}

{% block title %}Au'raw - FAQ{% endblock %}

{% block body %}

<div class="form__picture">
    <img src="{{ asset('static_pics/image67.jpg') }}" alt="beatuiful picture">

    <div class="form__container">
        <h1>Frequently Asked Questions</h1>
        <h3>Question 1</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus nostrum tenetur pariatur hic consequuntur. Placeat sint fuga veritatis consequatur.</p>
        <br>
        <h3>Question 2</h3>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Inventore voluptate non esse minima at placeat deleniti dolorum recusandae blanditiis repellat praesentium distinctio quos sit magnam, soluta fuga?</p>
        <br>
        <h3>Question 3</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus doloremque error voluptatum quia eaque ut magni fugit iste corporis beatae?</p>
        <br>
    </div>
</div>

{% endblock %}

templates/main/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Au'raw - Home{% endblock %}

{% block body %}
<div class="top-part__container">
    <div id="promo">
        {% if products|length > 3 %}
               <!-- Slideshow container -->
                <div class="slideshow-container">
                    {% for i in 0..3 %}
                    <!-- Full-width images with number and caption text -->
                
                    <div class="mySlides fade">
                        <div class="numbertext">{{ i + 1 }} / 4</div>
                            <a href="{{ path('product', {'id': products[i].id}) }}">
                                <img src="{{ asset('uploads/images/products/'~ products[i].icon) }}" atl="{{ products[i].imgAlt }}">
                            </a>
                        <div class="text">{{products[i].title}}</div>
                    </div>
                    {% endfor %}
                    <!-- Next and previous buttons -->
                    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                    <a class="next" onclick="plusSlides(1)">&#10095;</a>
                </div>
                
                <!-- The dots/circles -->
                <div style="text-align:center">
                    <span class="dot" onclick="currentSlide(1)"></span>
                    <span class="dot" onclick="currentSlide(2)"></span>
                    <span class="dot" onclick="currentSlide(3)"></span>
                    <span class="dot" onclick="currentSlide(4)"></span>
                </div>
            </div>
        {% endif %}
            <div id="sections">
                <div class="sections__tiles">
                    <div id="selection gluten-free">
                        <a href="{{ path('products_by_tag', {'id': 4}) }}">
                            <img src="{{ asset('static_pics/gluten-free-small12345.png') }}" alt="gluten-free desserts selection">
                        </a>
                    </div>
                    
                    <div id="selection nuts-free">
                        <a href="{{ path('products_by_tag', {'id': 1}) }}">
                            <img src="{{ asset('static_pics/nuts-free-small122345.png') }}" atl="no nuts desserts selection">
                        </a>
                    </div>
<!--
                    <div id="selection cocoa-free">
                        <img src="assets/Product-pictures/Final/cocoa-free.png" alt="cocoa-free desserts selection">
                    </div>
-->
                    <div id="selection low-cal">
                        <a href="{{ path('products_by_tag', {'id': 2}) }}">
                            <img src="{{ asset('static_pics/low-cal-small12345.png') }}" alt="low-calorie dessers selection">
                        </a>
                    </div>
            </div>
        </div>
</div>

<div class="bottom-part__container">
<div class="selection-description">
                <h1>The Best of Our Desserts</h1>
                <p>The marriage of freshest fruit, berries, and nuts gave birth to these wonderfully fresh and healthy desserts. Made with love and passion, they will certainly bring you joy!</p>
                <p>You can order them by sending us a message, giving us a call, or simply by dropping by our shop in Paris. We will be happy to answer all and any of your questions and guide you down the path of naturally good desserts!</p>
            </div>
        
{% for product in products %}
    <a href="{{ path('product', {'id': product.id}) }}" class="product">
        <div class="product-item">
            <img src="{{ asset('uploads/images/products/'~ product.icon) }}" atl="{{ product.imgAlt }}">
            <div class="name">
                <h1>{{ product.title }}</h1>
            </div>
            <div class="description">
                <p class="product-description">{{ product.shortDescription }}</p>
            </div>
                <p class="product-price--list">{{ product.priceEuro }}<sup>{{ "%02d"|format(product.priceCentime) }}</sup> &euro; <em>/ {{ product.unit.title }}</em></p>
        </div>
    </a>
{% endfor %}
</div>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="{{ asset('js/carousel.js') }}"></script>
{% endblock %}

templates/main/product.html.twig
{% extends 'base.html.twig' %}

{% block title %}Au'raw - {{ product.title }}{% endblock %}

{% block body %}

<div class="product__container">
            <div class="product__top">
                <div class="product-image">
                    <img src="{{ asset('uploads/images/products/'~ product.image) }}" atl="{{ product.imgAlt }}">
                    <img src="{{ asset('uploads/images/products/'~ product.icon) }}" atl="{{ product.imgAlt }}">
                </div>
                <div class="product-info">
                    <h1>{{ product.title }}</h1>
                    <div class="product-tags">
                    <ul class="tags">
                        {% for tag in product.tags %}
                            <li><a href="{{ path('products_by_tag', {'id': tag.id}) }}" class="tag">{{ tag.title }}</a></li>
                        {% endfor %}
                    </ul>
                    <div class="product-ingr">
                        
                        <div id="ingr">
                            <p>Ingredients:</p>
                            <ul>
                                {% for ingredient in product.ingredients %}
                                <li>{{ ingredient.title }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="product-details">
                            <p class="product-price">{{ product.priceEuro }}<sup>{{ "%02d"|format(product.priceCentime) }}</sup> &euro;</p><em> {{ product.unit.title }}</em>
                        </div>
                    </div>
                    <div class="order"><h4>You can order this product by <a href="{{ path('contact_us') }}">sending us a message</a>, giving us a call, or dropping by our shop in Paris!</h4>
                    </div>
                </div>
                </div>
                
            </div>

            <div class="product__bottom">
                <div class="product-description">
                    <p>{{ product.longDescription }}</p>
                    <h3>Allergens:</h3>
                    <ul>
                        {% for allergen in product.allergens %}
                            <li>{{ allergen.title }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>

{% endblock %}

templates/main/products_by_tag.html.twig
{% extends 'base.html.twig' %}

{% block title %}Au'raw - {{ tag.title }} products{% endblock %}

{% block body %}
<div class="top-part__container">
<h1>{{ tag.title }} products</h1>
</div>
<div class="bottom-part__container">
{% for product in tag.products %}
    {% if product.enabled == true %}
        <a href="{{ path('product', {'id': product.id}) }}" class="product">
            <div class="product-item">
                <img src="{{ asset('uploads/images/products/'~ product.icon) }}" atl="{{ product.imgAlt }}">
                <div class="name">
                    <h1>{{ product.title }}</h1>
                </div>
                <div class="description">
                    <p class="product-description">{{ product.shortDescription }}</p>
                    <p class="product-price--list">{{ product.priceEuro }}<sup>{{ "%02d"|format(product.priceCentime) }}</sup> &euro; <em>/ {{ product.unit.title }}</em></p>
                </div>
            </div>
        </a>
    {% endif %}
{% endfor %}
</div>
{% endblock %}